### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;

### ISSUE THREAD

**Issue by zhnagheng** [jeecgboot/autopoi#100]
<dependency>
      <groupId>org.jeecgframework</groupId>
      <artifactId>autopoi-web</artifactId>
      <version>1.4.7</version>
 </dependency>

when i use the util mathod org.jeecgframework.poi.excel.ExcelImportUtil#importExcel(java.io.InputStream, java.lang.Class<?>, org.jeecgframework.poi.excel.entity.ImportParams) to import a excel, it seems not work correctly, the error stack as following picture, 
i will appreciate for any response, hope your reply!!!
![image](https://github.com/jeecgboot/autopoi/assets/50563791/0dbdb8fe-72e4-49e3-9fa2-b9173fe096dc)

**Comment by zhangdaiscott** [comment]
你是不是自己升级了poi导致版本不一致，冲突了

**Comment by wxqlandy** [comment]
这个大概率是版本冲突了，autopoi的poi依赖有些太老了，我之前项目用了poi-tl框架操作word，就存在版本冲突了，导致新版的poi-tl没法用，报的错也基本上是上面这种，各种类或者方法找不到，只能回去旧版，希望autopoi能够更新下poi依赖
