### ISSUE TITLE
导入报错：NET:ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by 1578393930** [jeecgboot/autopoi#135]
导入excel时报错，NET:ERR_CONNECTION_RESET。经测试本地环境时么有问题，但是到线上环境(https,nginx)时就会报这个错，目前排查排除的问题文件大小不超出限制(2M),上传也不超时，这还会是哪里的问题呀。
![Snipaste_2024-12-16_16-48-44](https://github.com/user-attachments/assets/d5a45720-7269-4aa2-8856-7eff7fd4182b)

**Comment by zhangdaiscott** [comment]
看看是不是nginx配置限制了最大上传
