### ISSUE TITLE
@ExcelCollection多对多

### ISSUE THREAD

**Issue by ysfcore** [jeecgboot/autopoi#48]
一对多导出实体注解源码中，
有没有这种：一个实体类中@ExcelCollection(name="客户")，但是客户这个实体类中还有类似的@ExcelCollection(name="子客户")
就是多对多的情况
不知道有没有描述清楚
![image](https://user-images.githubusercontent.com/55525000/123552702-d6e97100-d7a9-11eb-9bbb-0b833b380549.png)

**Comment by wanghui19970715** [comment]
有找到解决方法吗？也遇到了这个问题

**Comment by huangtao261** [comment]
求解决办法

**Comment by wanghui19970715** [comment]
> 求解决办法

没什么好的办法的话，就换成easypoi吧，easypoi-4.4.0版本多对多是没有问题的

**Comment by huangtao261** [comment]
> > 求解决办法
> 
> 没什么好的办法的话，就换成easypoi吧，easypoi-4.4.0版本多对多是没有问题的

ok , 谢谢大佬

**Comment by wtus** [comment]
> > 求解决办法
> 
> 没什么好的办法的话，就换成easypoi吧，easypoi-4.4.0版本多对多是没有问题的

谢了，用 4.1.0 版本搞了一天了，靠，升级4.4.0 就好了
