### ISSUE TITLE
根据模板导出excel时@Dict注解不起作用

### ISSUE THREAD

**Issue by HWGALLEN** [jeecgboot/autopoi#72]
POI版本号：3.4.4

用自定义的excel模板导出数据的时候，部分字段用的是从其他表中查询的结果，记录的值为id，显示的是对应字段的内容，例如：字段名称：sex，id=123，text=男。用自定义模板导出的excel表格，需要导出的内容为“男”，实际导出的是“123”，这个字段不会自动转换为显示的内容，而依然是记录的内容。这个有没有什么解决方法？
![image](https://user-images.githubusercontent.com/23203833/203354714-0c3099d1-a4f2-4257-91ca-30e3734c8385.png)
![image](https://user-images.githubusercontent.com/23203833/203354749-305aefd4-b32b-4bfc-96d6-78c25c41b822.png)
![image](https://user-images.githubusercontent.com/23203833/203354787-e5cfaf9a-5e8a-4ead-9b9b-b0b2599e2e87.png)
![image](https://user-images.githubusercontent.com/23203833/203354800-d182f126-4a3f-40eb-81d6-137b3df3f861.png)

**Comment by zhangdaiscott** [comment]
这个逻辑里面不支持注解
