### ISSUE TITLE
ExcelImportUtil.importExcelBySax导入数据解析不到数据

### ISSUE THREAD

**Issue by Evan98521** [jeecgboot/autopoi#85]
ExcelImportUtil.importExcelBySax，使用importExcelBySax导入数据解析不到数据，得到的list数据是空的。

>     public Result<?> importExcel(HttpServletRequest request, HttpServletResponse response, Class<Uers> clazz) throws Exception  { 
>       MultipartHttpServletRequest multipartRequest = (MultipartHttpServletRequest) request;         
>       Map<String, MultipartFile> fileMap = multipartRequest.getFileMap();     
>       for (Map.Entry<String, MultipartFile> entity : fileMap.entrySet()) {             
>         MultipartFile file = entity.getValue();         
>         ImportParams params = new ImportParams();         
>         params.setTitleRows(1);          
>         params.setHeadRows(1);           
>         params.setNeedSave(true);          
>         List<Uers> list = ExcelImportUtil.importExcelBySax(file.getInputStream(), clazz, params);

**Comment by nowtostudeyday** [comment]
我也存在这个问题，使用inportExcel()可以正常导入，但是使用inportExcelBySax()就无法获取到数据

**Comment by EightMonth** [comment]
ImportParams需要设置SheetNum，否则是读取0行
	/**
	 * 上传表格需要读取的sheet 数量,默认为0
	 */
	private int sheetNum = 0;

**Comment by nowtostudeyday** [comment]
好的，谢谢！




1375932459
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/autopoi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月23日(星期四) 中午1:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/autopoi] ExcelImportUtil.importExcelBySax导入数据解析不到数据 (Issue #85)





 
ImportParams需要设置SheetNum，否则是读取0行
 /**
 * 上传表格需要读取的sheet 数量,默认为0
 */
 private int sheetNum = 0;

**Comment by yjs123456** [comment]
为什么我加上了也不好使呢，
ImportParams params = new ImportParams();
        params.setTitleRows(0);
        params.setHeadRows(1);
        params.setStartSheetIndex(0);
        params.setSheetNum(1);
        params.setStartRows(1);
        params.setNeedSave(true);

        List<Map<String, Object>> list = ExcelImportUtil.importExcelBySax(inputStream, Map.class, params);
输出：
[{}, {}, {}, {}, {}, {}, {}, {}, {}]
